#### Base parametres ####
baseURL = 'http://fabandmina.github.io/'
title = 'Fab and Mina'
theme = "huguette-fabandmina"
copyright = "Copyright 2022-{year} Fabien TRAN VAN HUNG All rights reserved."
sectionPagesMenu = "main"

### Languages configuration ###
languageCode = 'en-us'
defaultContentLanguage = 'en'

disableLanguages = ['jp']

[languages]
  [languages.en]
    title = "Fab and Mina"
    languageName = "🇬🇧"
    weight = 1
  
  [languages.fr]
    title = "Fab et Mina"
    languageName = "🇫🇷"
    weight = 2
    [[languages.fr.menu.main]]
      url = '/trip/'
      name = 'Voyages'
    [[languages.fr.menu.main]]
      url = '/gears/'
      name = 'Équipements'
    [[languages.fr.menu.main]]
      url = '/contact/'
      name = 'Contacts'
    [[languages.fr.menu.main]]
      url = '/about/'
      name = 'À propos'
    [[languages.fr.menu.main]]
      url = '/support/'
      name = 'Aidez-nous'

  [languages.jp]
    title = "ファブトミナ"
    languageName = "🇯🇵"
    weight = 3



[params]
  css = true
  instagram_link = "https://www.instagram.com/fabandmina/"
  francetvinfo_link = "http://la1ere.francetvinfo.fr/nouvellecaledonie/caledoniens-ailleurs-fabien-nomade-suspens-850376.html?fbclid=IwAR2SR_-OBBLVUra7L8jkOvHtHwkKLXs1taky8WGmbf3ixXeQz4rO6vFZm20"
  banner = "https://piskel-imgstore-b.appspot.com/img/be7f5db3-44e7-11ed-8f4b-efcdd3f462cf.gif"
  subtitle = "Around the world!"
  logo = "https://piskel-imgstore-b.appspot.com/img/bce8f69c-44e3-11ed-92e2-efcdd3f462cf.gif"
  avatar_fab = "https://piskel-imgstore-b.appspot.com/img/3c6deca1-4506-11ed-9f66-df2e8d43b92e.gif"
  avatar_mina = "https://piskel-imgstore-b.appspot.com/img/db2facdc-4505-11ed-ac5a-df2e8d43b92e.gif"
  avatar_fabandmina = "https://piskel-imgstore-b.appspot.com/img/7d794b91-4506-11ed-bd5b-df2e8d43b92e.gif"


  [params.shareButtons]
    networks = [ "facebook", "twitter", "tumblr", "email", "reddit", "whatsapp", "telegram" ]
    size = "small"
    icon = "solid"
    buttonMargin = "0.2em"

[markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.main]]
  identifier = 'trip'
  name = 'Trips'
  url = '/trip/'
  weight = -501

[[menu.main]]
  identifier = 'gears'
  name = 'Gears'
  url = '/gears/'
  weight = -500

[[menu.main]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact/'
  weight = -112

[[menu.main]]
  identifier = 'about'
  name = 'About Us'
  url = '/about/'
  weight = -111

[[menu.main]]
  identifier = 'support'
  name = 'Support Us'
  url = '/support/'
  weight = -110
