baseURL = 'http://fabandmina.github.io/'
languageCode = 'en-us'
title = 'Fab and Mina'
theme = "huguette-fabandmina"

copyright = "Copyright 2007-{year} Fabien TRAN VAN HUNG All rights reserved."
sectionPagesMenu = "main"

[params]
css = true
instagram_link = "https://www.instagram.com/fabandmina/"
francetvinfo_link = "http://la1ere.francetvinfo.fr/nouvellecaledonie/caledoniens-ailleurs-fabien-nomade-suspens-850376.html?fbclid=IwAR2SR_-OBBLVUra7L8jkOvHtHwkKLXs1taky8WGmbf3ixXeQz4rO6vFZm20"


  [params.shareButtons]
  networks = [ "facebook", "twitter", "tumblr", "email", "reddit", "whatsapp", "telegram" ]
  size = "small"
  icon = "solid"
  buttonMargin = "0.2em"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
  identifier = 'trip'
  name = 'Trips'
  url = '/trip/'
  weight = -501

[[menu.main]]
  identifier = 'gears'
  name = 'Gears'
  url = '/gears/'
  weight = -500

[[menu.main]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact/'
  weight = -112

[[menu.main]]
  identifier = 'about'
  name = 'About Us'
  url = '/about/'
  weight = -111

[[menu.main]]
  identifier = 'support'
  name = 'Support Us'
  url = '/support/'
  weight = -110
