#### Base parametres ####
baseurl ='http://fabandmina.github.io/'
title = 'Fab and Mina'
theme = "huguette-fabandmina"
copyright = "Copyright 2022-{year} Fabien TRAN VAN HUNG All rights reserved."
sectionPagesMenu = "main"

### Languages configuration ###
defaultContentLanguage = 'en'
disableLanguages = ['jp']

[languages]

  ### English ###
  [languages.en]
    languageCode = 'en'
    title = "Fab and Mina"
    languageName = "🇬🇧 English"
    weight = 1
    [[languages.en.menu.main]]
      identifier = 'home'
      name = 'Home'
      pageref ='/'
      weight = 1
    [[languages.en.menu.main]]
      identifier = 'trip'
      name = 'Trips'
      pageref ='/trip'
      weight = 2
    [[languages.en.menu.main]]
      identifier = 'gears'
      name = 'Gears'
      pageref ='/gears'
      weight = 3
    [[languages.en.menu.main]]
      identifier = 'contact'
      name = 'Contact'
      pageref ='/contact'
      weight = 4
    [[languages.en.menu.main]]
      identifier = 'about'
      name = 'About Us'
      pageref ='/about'
      weight = 5
    [[languages.en.menu.main]]
      identifier = 'support'
      name = 'Support Us'
      pageref ='/support'
      weight = 6

  ### French ###
  [languages.fr]
    languageCode = 'fr'
    title = "Fab et Mina"
    languageName = "🇫🇷 Français"
    weight = 2
    [[languages.fr.menu.main]]
      identifier = 'home'
      name = 'Accueil'
      pageref ='/'
      weight = 1
    [[languages.fr.menu.main]]
      identifier = 'trip'
      pageref ='/trip/'
      name = 'Voyages'
      weight = 2
    [[languages.fr.menu.main]]
      identifier = 'gears'
      pageref ='/gears'
      name = 'Équipements'
      weight = 3
    [[languages.fr.menu.main]]
      identifier = 'contact'
      pageref ='/contact'
      name = 'Contacts'
      weight = 4
    [[languages.fr.menu.main]]
      identifier = 'about'
      pageref ='/about'
      name = 'À propos'
      weight = 5
    [[languages.fr.menu.main]]
      identifier = 'support'
      pageref ='/support'
      name = 'Aidez-nous'
      weight = 6
  
  ### Japanese ###
  [languages.jp]
    title = "ファブトミナ"
    languageName = "🇯🇵 日本語"
    weight = 3



### Other parametres ###
[params]
  css = true

  ### Banner & header ###
  banner_dark="https://media.githubusercontent.com/media/fabandmina/piskel-projects/main/fabandmina/render/fabandmina_banner_dark.gif"
  banner = "https://media.githubusercontent.com/media/fabandmina/piskel-projects/main/fabandmina/render/fabandmina_banner_light.gif"
  subtitle = "Around the world!"
  logo = "https://media.githubusercontent.com/media/fabandmina/piskel-projects/main/fabandmina/render/fabandmina_logo.png"
  
  ### Avatars ###
  avatar_fab = "https://media.githubusercontent.com/media/fabandmina/piskel-projects/main/fabandmina/render/fabandmina_fab.gif"
  avatar_mina = "https://media.githubusercontent.com/media/fabandmina/piskel-projects/main/fabandmina/render/fabandmina_mina.gif"
  avatar_fabandmina = "https://media.githubusercontent.com/media/fabandmina/piskel-projects/main/fabandmina/render/fabandmina_together.gif"

  ### Icons ###
  icon_food = "https://media.githubusercontent.com/media/fabandmina/piskel-projects/main/fabandmina/render/fabandmina_food.png"

  ### shareButtons ###
  [params.shareButtons]
    networks = [ "facebook", "twitter", "tumblr", "email", "reddit", "whatsapp", "telegram" ]
    size = "small"
    icon = "solid"
    buttonMargin = "0.2em"

  ### Social media ###
  [params.instagram_link] 
    url = "https://www.instagram.com/fabandmina/"
    icon = "fa-brands fa-instagram"
  [params.francetvinfo_link] 
    url = "http://la1ere.francetvinfo.fr/nouvellecaledonie/caledoniens-ailleurs-fabien-nomade-suspens-850376.html?fbclid=IwAR2SR_-OBBLVUra7L8jkOvHtHwkKLXs1taky8WGmbf3ixXeQz4rO6vFZm20"
    icon = "fa-regular fa-newspaper"
  [params.flickr_link]
    url = "https://www.flickr.com/photos/196589873@N03/albums"
    icon = "fa-brands fa-flickr"

### Enable shortcode in .md ###
[markup.goldmark.renderer]
  unsafe = true
