backend:
  name: git-gateway
  branch: staging # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'trips'
    label: 'Trips'
    folder: 'content/blogs/trip'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Description', name: 'introduction', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail URL', name: 'thumbnail', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: false, default: ["trips"] }
      - { label: 'Flickr album URL', name: 'flickr_album', widget: 'string' }
      - { label: 'Map URL', name: 'map', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown', default: false }
  - name: 'gears'
    label: 'Gears'
    folder: 'content/blogs/gears'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Description', name: 'introduction', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail URL', name: 'thumbnail', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: false, default: ["gears"] }
      - { label: 'Flickr album URL', name: 'flickr_album', widget: 'string' }
      - { label: 'Map URL', name: 'map', widget: 'string' }
      - { label: 'Is draft', name: 'draft', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown', default: false }